### ISSUE TITLE
Deep RL Bootcamp

### ISSUE THREAD

**Issue by Fujiki-Nakamura** [Fujiki-Nakamura/Fujiki-Nakamura.github.io#3]
## TODO
- [ ] Lecture 7 SVG, DDPG, and Stochastic Computation Graphs (John Schulman)
- [ ] Lecture 8 Derivative Free Methods
- [ ] Lecture 10b Inverse RL -- Chelsea Finn
- [ ] Frontiers Lecture I: Recent Advances, Frontiers and Future of Deep RL -- Vlad Mnih
- [ ] Frontiers Lecture II: Recent Advances, Frontiers and Future of Deep RL -- Sergey Levine
